version: "3"

services:
  message-pusher:
    build:
      context: .
      dockerfile: Dockerfile
    image: message-pusher:alpine
    restart: unless-stopped
    ports:
      - 33000:3000
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro