version: "3"

services:
  message-pusher:
    image: ghcr.io/rain-kl/message-pusher:v0.4.12.1
    restart: unless-stopped
    ports:
      - 23000:3000
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - pusher_data:/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  pusher_data: